<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<ApplicationIcon>Assets\SoftwareIcon.ico</ApplicationIcon>
		<AssemblyName>QuickMask</AssemblyName>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>none</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Material.Icons.Avalonia" Version="3.0.2" />
		<PackageReference Include="SukiUI" Version="7.0.2-nightly20260801" />
		<ProjectReference Include="..\QuickMask.Core\QuickMask.Core.csproj" />
		<PackageReference Include="ReactiveUI.SourceGenerators" Version="3.2.0" PrivateAssets="all" />
		<PackageReference Include="SkiaSharp" Version="4.151.2" />
		<PackageReference Include="Avalonia" Version="12.1.2" />
		<PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
		<PackageReference Include="ReactiveUI.Avalonia" Version="12.1.1" />

		<Content Include="..\QuickMask.Core\Data\Localization\**\*.json">
			<Link>locales\%(RecursiveDir)%(Filename)%(Extension)</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</Content>

		<AvaloniaResource Include="Assets\Internal\**" />
	</ItemGroup>
</Project>
