/// ****************************************************************************************************
///
/// <auto-generated>
///     This file was generated during the build process from shared locale data (Data/Localization/ja-JP.json).
///     DO NOT EDIT THIS FILE MANUALLY.
///
///     To regenerate, run `dotnet run` in the LocalizationKeyGenerator project
///     or build the QuickMask.Core project.
/// </auto-generated>
///
/// ****************************************************************************************************

namespace QuickMask.Core.Localization;

public static class Loc
{
    public const string LanguageName = "LanguageName";
    public const string LanguagePriority = "LanguagePriority";
    public static class Main
    {
        public static class MenuBar
        {
            public static class UVImage
            {
                public const string Title = "Main.MenuBar.UVImage.Title";
                public const string UnloadUV = "Main.MenuBar.UVImage.UnloadUV";
            }
            public static class Tool
            {
                public const string Title = "Main.MenuBar.Tool.Title";
                public const string SelectAllObject = "Main.MenuBar.Tool.SelectAllObject";
            }
        }
        public static class SourceTexture
        {
            public const string Label = "Main.SourceTexture.Label";
        }
        public static class MaskTexture
        {
            public const string Label = "Main.MaskTexture.Label";
        }
        public const string LoadImage = "Main.LoadImage";
        public const string LoadUVImage = "Main.LoadUVImage";
        public const string GenerateMask = "Main.GenerateMask";
    }
    public static class Warning
    {
        public const string SelectAllObjectsWithoutUV = "Warning.SelectAllObjectsWithoutUV";
    }
    public static class SelectionArea
    {
        public const string Title = "SelectionArea.Title";
        public const string Description = "SelectionArea.Description";
        public static class AreaType
        {
            public const string Selection = "SelectionArea.AreaType.Selection";
            public const string Eraser = "SelectionArea.AreaType.Eraser";
        }
        public const string PixelCount = "SelectionArea.PixelCount";
        public static class ContextMenu
        {
            public const string ToggleAreaType = "SelectionArea.ContextMenu.ToggleAreaType";
            public const string Remove = "SelectionArea.ContextMenu.Remove";
        }
        public const string ClearSelection = "SelectionArea.ClearSelection";
    }
}
