/// ****************************************************************************************************
///
/// <auto-generated>
///     This file was generated during the build process from shared locale data (Data/Localization/ja-JP.json).
///     DO NOT EDIT THIS FILE MANUALLY.
///
///     To regenerate, run `dotnet run` in the LocalizationKeyGenerator project
///     or build the QuickMask.Core project.
/// </auto-generated>
///
/// ****************************************************************************************************

namespace QuickMask.Core.Localization;

public static class Loc
{
    public const string LanguageName = "LanguageName";
    public const string LanguagePriority = "LanguagePriority";
    public static class WindowTitle
    {
        public const string Base = "WindowTitle.Base";
        public const string UvGuideLoaded = "WindowTitle.UvGuideLoaded";
        public const string UvGuideNotLoaded = "WindowTitle.UvGuideNotLoaded";
        public const string SelectionAreaCount = "WindowTitle.SelectionAreaCount";
    }
    public static class Main
    {
        public static class MenuBar
        {
            public static class UVImage
            {
                public const string Title = "Main.MenuBar.UVImage.Title";
                public const string UnloadUV = "Main.MenuBar.UVImage.UnloadUV";
            }
            public static class Tool
            {
                public const string Title = "Main.MenuBar.Tool.Title";
                public const string DetectAllObjects = "Main.MenuBar.Tool.DetectAllObjects";
            }
        }
        public static class SourceTexture
        {
            public const string Label = "Main.SourceTexture.Label";
        }
        public static class MaskTexture
        {
            public const string Label = "Main.MaskTexture.Label";
            public static class PreviewMode
            {
                public const string Mask = "Main.MaskTexture.PreviewMode.Mask";
                public const string Overlay = "Main.MaskTexture.PreviewMode.Overlay";
            }
        }
        public const string LoadImage = "Main.LoadImage";
        public const string LoadUVImage = "Main.LoadUVImage";
        public const string GenerateMask = "Main.GenerateMask";
    }
    public static class SelectionArea
    {
        public const string Title = "SelectionArea.Title";
        public const string Description = "SelectionArea.Description";
        public static class AreaType
        {
            public const string Selection = "SelectionArea.AreaType.Selection";
            public const string Eraser = "SelectionArea.AreaType.Eraser";
        }
        public const string PixelCount = "SelectionArea.PixelCount";
        public static class ContextMenu
        {
            public const string ToggleAreaType = "SelectionArea.ContextMenu.ToggleAreaType";
            public const string Remove = "SelectionArea.ContextMenu.Remove";
        }
        public const string ClearSelection = "SelectionArea.ClearSelection";
    }
    public static class Success
    {
        public static class SelectionArea
        {
            public const string Added = "Success.SelectionArea.Added";
            public const string AddedMultiple = "Success.SelectionArea.AddedMultiple";
        }
        public static class BackgroundPoint
        {
            public const string Set = "Success.BackgroundPoint.Set";
        }
        public const string MaskSaved = "Success.MaskSaved";
    }
    public static class Error
    {
        public const string NoImageLoaded = "Error.NoImageLoaded";
        public static class ImageSelector
        {
            public const string InvalidBackgroundPoint = "Error.ImageSelector.InvalidBackgroundPoint";
            public const string DimensionMismatch = "Error.ImageSelector.DimensionMismatch";
            public const string GuideImageSizeMismatch = "Error.ImageSelector.GuideImageSizeMismatch";
            public const string NotProperlyInitialized = "Error.ImageSelector.NotProperlyInitialized";
            public const string InvalidSelectionPoint = "Error.ImageSelector.InvalidSelectionPoint";
            public const string PointNotSelectable = "Error.ImageSelector.PointNotSelectable";
        }
        public static class MaskGenerator
        {
            public const string InvalidMaskDimensions = "Error.MaskGenerator.InvalidMaskDimensions";
            public const string MaskGenerationFailed = "Error.MaskGenerator.MaskGenerationFailed";
            public const string MaskSaveFailed = "Error.MaskGenerator.MaskSaveFailed";
        }
    }
}
